# Generated by Django 3.2.5 on 2021-07-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='type',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
