# Generated by Django 3.2.5 on 2021-07-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='status',
            new_name='available',
        ),
    ]
