# Generated by Django 3.2.5 on 2021-07-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0022_borrow_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='slug',
        ),
    ]
