# Generated by Django 3.2.5 on 2021-07-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0024_alter_borrow_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['book']},
        ),
    ]
