# Generated by Django 3.2.5 on 2021-07-18 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0027_alter_borrow_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.book'),
        ),
    ]
